name: Flathub release
on:
  push:

defaults:
  run:
    working-directory: wger

jobs:
  setup:
    name: Setup
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
        with:
          path: wger

      - name: Checkout flathub repo
        uses: actions/checkout@v3
        with:
          repository: wger-project/test
          path: flathub
      - name: Setup Java
        uses: actions/setup-java@v1
        with:
          java-version: 17.x

      - name: Setup Flutter
        uses: subosito/flutter-action@v1
        with:
          channel: 'stable'
          flutter-version: '3.7.x'

      - name: Decrypt config files
        run: |
          cd ./fastlane/metadata/envfiles
          chmod +x ./decrypt_secrets.sh
          ./decrypt_secrets.sh
        env:
          DECRYPTKEY_PLAYSTORE: ${{ secrets.DECRYPTKEY_PLAYSTORE }}
          DECRYPTKEY_PLAYSTORE_SIGNING_KEY: ${{ secrets.DECRYPTKEY_PLAYSTORE_SIGNING_KEY }}
          DECRYPTKEY_PROPERTIES: ${{ secrets.DECRYPTKEY_PROPERTIES }}

      - name: Flutter info
        run: |
          dart --version
          flutter --version

      - name: Install Flutter dependencies
        run: flutter pub get

      - name: Build application for linux
        run: |
          sudo apt install -y clang cmake ninja-build pkg-config libgtk-3-dev liblzma-dev libstdc++-12-dev
          flutter build linux --release
          cd flatpak/scripts
          dart pub get
          dart flatpak_packager.dart --meta ../flatpak_meta.json --github -n pubspec.yaml
          dart manifest_generator.dart --meta ../flatpak_meta.json --github -n pubspec.yaml
          
          cp flatpak_generator_exports/de.wger.flutter.json ../../../flathub
          ls flatpak_generator_exports/wger-linux-x86_64.sha256
          ls flatpak_generator_exports/wger-linux-x86_64.tar.gz
        env:
          WGER_API_KEY: ${{ secrets.WGER_API_KEY }}

      - name: Push to flathub repository
        uses: cpina/github-action-push-to-another-repository@main
        env:
          SSH_DEPLOY_KEY: ${{ secrets.SSH_DEPLOY_KEY }}
        with:
          source-directory: 'flathub'
          destination-github-username: 'wger-project'
          destination-repository-name: 'test'
          user-email: github-actions@github.com
          target-branch: master
          commit-message: Update de.wger.flutter.json

      - name: Upload generated flatpak archive
        uses: actions/upload-artifact@v3
        with:
          name: Flatpak file
          path: wger/flatpak/scripts/flatpak_generator_exports/wger-linux-x86_64.tar.gz

      - name: Upload SHA256 checksum archive
        uses: actions/upload-artifact@v3
        with:
          name: Flatpak file
          path: wger/flatpak/scripts/flatpak_generator_exports/wger-linux-x86_64.sha256

      #- name: Build AAB
      #  run: flutter build appbundle --release
      #  env:
      #    WGER_API_KEY: ${{ secrets.WGER_API_KEY }}

      #- name: Upload generated aab archive
      #  uses: actions/upload-artifact@v3
      #  with:
      #    name: AAB file
      #    path: wger/build/app/outputs/bundle/release/app-release.aab